teststandv2:
  # Publish all joint states -----------------------------------
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  # Joint Trajectory Controllers -------------------------------
  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - slider
          - l1
          - l2
          - l3

      gains:
        slider : {p: 100.0, i: 0.01, d: 10.0}
        l1 : {p: 100.0, i: 0.01, d: 10.0}
        l2 : {p: 100.0, i: 0.01, d: 10.0}
        l3 : {p: 100.0, i: 0.01, d: 10.0}