legv1:
  # Publish all joint states -----------------------------------
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  # Joint Trajectory Controllers -------------------------------
  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - slider
          - j1
          - j2
          - j3

      gains:
        slider : {p: 100.0, i: 0.01, d: 10.0}
        j1 : {p: 100.0, i: 0.01, d: 10.0}
        j2 : {p: 100.0, i: 0.01, d: 10.0}
        j3 : {p: 100.0, i: 0.01, d: 10.0}